/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniJikken */

#ifndef _Included_JniJikken
#define _Included_JniJikken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniJikken
 * Method:    copy
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JniJikken_copy
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
